package win32

import "syscall"

var (
	user32   = syscall.NewLazyDLL("user32.dll")
	kernel32 = syscall.NewLazyDLL("kernel32.dll")
	shell32  = syscall.NewLazyDLL("shell32.dll")
	gdi32    = syscall.NewLazyDLL("gdi32.dll")
	ole32    = syscall.NewLazyDLL("ole32.dll")
	dwmapi   = syscall.NewLazyDLL("dwmapi.dll")
	psapi    = syscall.NewLazyDLL("psapi.dll")

	procCreateMutexW       = kernel32.NewProc("CreateMutexW")
	procCloseHandle        = kernel32.NewProc("CloseHandle")
	procGetLastError       = kernel32.NewProc("GetLastError")
	procGetCurrentThreadId = kernel32.NewProc("GetCurrentThreadId")
	procGetModuleHandleW   = kernel32.NewProc("GetModuleHandleW")
	procOpenProcess        = kernel32.NewProc("OpenProcess")

	procRegisterClassExW           = user32.NewProc("RegisterClassExW")
	procCreateWindowExW            = user32.NewProc("CreateWindowExW")
	procDefWindowProcW             = user32.NewProc("DefWindowProcW")
	procDestroyWindow              = user32.NewProc("DestroyWindow")
	procDispatchMessageW           = user32.NewProc("DispatchMessageW")
	procTranslateMessage           = user32.NewProc("TranslateMessage")
	procGetMessageW                = user32.NewProc("GetMessageW")
	procPostQuitMessage            = user32.NewProc("PostQuitMessage")
	procPostMessageW               = user32.NewProc("PostMessageW")
	procPostThreadMessageW         = user32.NewProc("PostThreadMessageW")
	procSetWindowsHookExW          = user32.NewProc("SetWindowsHookExW")
	procCallNextHookEx             = user32.NewProc("CallNextHookEx")
	procUnhookWindowsHookEx        = user32.NewProc("UnhookWindowsHookEx")
	procEnumWindows                = user32.NewProc("EnumWindows")
	procIsWindow                   = user32.NewProc("IsWindow")
	procIsWindowVisible            = user32.NewProc("IsWindowVisible")
	procIsIconic                   = user32.NewProc("IsIconic")
	procGetWindowTextLengthW       = user32.NewProc("GetWindowTextLengthW")
	procGetWindowTextW             = user32.NewProc("GetWindowTextW")
	procGetWindowThreadProcessId   = user32.NewProc("GetWindowThreadProcessId")
	procGetWindowLongPtrW          = user32.NewProc("GetWindowLongPtrW")
	procGetWindow                  = user32.NewProc("GetWindow")
	procGetAncestor                = user32.NewProc("GetAncestor")
	procGetLastActivePopup         = user32.NewProc("GetLastActivePopup")
	procGetWindowRect              = user32.NewProc("GetWindowRect")
	procShowWindow                 = user32.NewProc("ShowWindow")
	procShowWindowAsync            = user32.NewProc("ShowWindowAsync")
	procSetForegroundWindow        = user32.NewProc("SetForegroundWindow")
	procGetForegroundWindow        = user32.NewProc("GetForegroundWindow")
	procGetDC                      = user32.NewProc("GetDC")
	procGetWindowDC                = user32.NewProc("GetWindowDC")
	procReleaseDC                  = user32.NewProc("ReleaseDC")
	procSetWindowPos               = user32.NewProc("SetWindowPos")
	procSetLayeredWindowAttributes = user32.NewProc("SetLayeredWindowAttributes")
	procInvalidateRect             = user32.NewProc("InvalidateRect")
	procLoadIconW                  = user32.NewProc("LoadIconW")
	procSetWinEventHook            = user32.NewProc("SetWinEventHook")
	procUnhookWinEvent             = user32.NewProc("UnhookWinEvent")
	procRegisterWindowMessageW     = user32.NewProc("RegisterWindowMessageW")
	procCreatePopupMenu            = user32.NewProc("CreatePopupMenu")
	procAppendMenuW                = user32.NewProc("AppendMenuW")
	procDestroyMenu                = user32.NewProc("DestroyMenu")
	procTrackPopupMenu             = user32.NewProc("TrackPopupMenu")
	procGetCursorPos               = user32.NewProc("GetCursorPos")
	procBeginPaint                 = user32.NewProc("BeginPaint")
	procEndPaint                   = user32.NewProc("EndPaint")
	procFillRect                   = user32.NewProc("FillRect")
	procDrawIconEx                 = user32.NewProc("DrawIconEx")
	procDrawTextW                  = user32.NewProc("DrawTextW")
	procMonitorFromWindow          = user32.NewProc("MonitorFromWindow")
	procGetMonitorInfoW            = user32.NewProc("GetMonitorInfoW")
	procSendInput                  = user32.NewProc("SendInput")
	procGetClassNameW              = user32.NewProc("GetClassNameW")
	procSendMessageTimeoutW        = user32.NewProc("SendMessageTimeoutW")
	procGetClassLongPtrW           = user32.NewProc("GetClassLongPtrW")
	procDestroyIcon                = user32.NewProc("DestroyIcon")

	procShellNotifyIconW = shell32.NewProc("Shell_NotifyIconW")
	procSHGetFileInfoW   = shell32.NewProc("SHGetFileInfoW")
	procShellExecuteW    = shell32.NewProc("ShellExecuteW")

	procCreateSolidBrush       = gdi32.NewProc("CreateSolidBrush")
	procCreateCompatibleDC     = gdi32.NewProc("CreateCompatibleDC")
	procDeleteDC               = gdi32.NewProc("DeleteDC")
	procCreateCompatibleBitmap = gdi32.NewProc("CreateCompatibleBitmap")
	procSelectObject           = gdi32.NewProc("SelectObject")
	procBitBlt                 = gdi32.NewProc("BitBlt")
	procStretchBlt             = gdi32.NewProc("StretchBlt")
	procSetStretchBltMode      = gdi32.NewProc("SetStretchBltMode")
	procDeleteObject           = gdi32.NewProc("DeleteObject")
	procSetBkMode              = gdi32.NewProc("SetBkMode")
	procSetTextColor           = gdi32.NewProc("SetTextColor")
	procGetStockObject         = gdi32.NewProc("GetStockObject")

	procCoInitializeEx   = ole32.NewProc("CoInitializeEx")
	procCoUninitialize   = ole32.NewProc("CoUninitialize")
	procCoCreateInstance = ole32.NewProc("CoCreateInstance")

	procDwmGetWindowAttribute = dwmapi.NewProc("DwmGetWindowAttribute")
	procPrintWindow           = user32.NewProc("PrintWindow")
	procGetModuleFileNameExW  = psapi.NewProc("GetModuleFileNameExW")
)
